services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: vigil
      POSTGRES_USER: vigil
      POSTGRES_PASSWORD: vigil_secret
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U vigil" ]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 10s
      timeout: 5s
      retries: 5

  # -------------------------
  # BACKEND (FastAPI)
  # -------------------------
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: vigil-backend
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      minio:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql+asyncpg://vigil:vigil_secret@postgres:5432/vigil
      REDIS_URL: redis://redis:6379/0
      CELERY_BROKER_URL: redis://redis:6379/1
      MINIO_ENDPOINT: minio:9000

  # -------------------------
  # ML SERVICE (Celery worker)
  # -------------------------
  ml-service:
    build:
      context: .
      dockerfile: ml-service/Dockerfile
    container_name: vigil-ml
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
    environment:
      CELERY_BROKER_URL: redis://redis:6379/1
      DATABASE_URL: postgresql://vigil:vigil_secret@postgres:5432/vigil
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: vigil-media
      MINIO_SECURE: false
      DEVICE: cpu


volumes:
  postgres_data:
  redis_data:
  minio_data:
