"""update_videos_table_status_column

Revision ID: 9c28a44a1bf2
Revises: c1fa7f41301f
Create Date: 2026-05-22 17:33:13.208715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c28a44a1bf2'
down_revision: Union[str, Sequence[str], None] = 'c1fa7f41301f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
